#生产环境的配置
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

  #jpa配置：表结构自动更新，显示sql语句
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

#日志级别配置，位置配置
logging:
  level:
    root: warn
    com.sise: info
  file: log/blog-pro.log

#生产环境的端口号
server:
  port: 8081