#开发环境配置
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

  #jpa配置：表结构自动更新，显示sql语句
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#日志级别配置，位置配置
logging:
  level:
    root: info
    com.sise: debug
  file: log/blog-dev.log